{% set name = "pypika-gis" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypika-gis-{{ version }}.tar.gz
  sha256: ae1b26d383ee3c1546da03b7e4e31906d899db9a45d7af480b7eb87e036ca172

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip <21.3
    - python {{ python_min }}
    - poetry >=0.12
  run:
    - pypika <1.0.0
    - python >={{ python_min }}

test:
  imports:
    - pypika_gis
    - pypika_gis.dialects
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/eduardogspereira/pypika-gis
  summary: SpatialTypes functions for extend PyPika with GIS
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mccarthyryanc
